import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Typography from "../components/Typography";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography size={3} gutter={0}>
          Hello! my name is Joel,
        </Typography>
        <Typography><Typography size={3}>
          a software engineer based in Philippines.
        </Typography></Typography>
        <Typography component="h1" size={10} weight={700} gutter={1}>
          I help teams build beautiful apps through writing dev-friendly and
          user-friendly software.
        </Typography>
        <div
          style={{
            display: "flex",
            gap: "8px",
          }}
        >
          <Button filled iconTrailing="waving_hand" size="large">
            Say hello!
          </Button>
          <Button iconTrailing="arrow_forward" size="large">
            See receipts
          </Button>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
