import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import ContactForm from "../components/ContactForm";
import Typography from "../components/Typography";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section
          className={styles.section}
          style={{
            background: "#efebe9",
          }}
        >
          <div>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                placeContent: "center",
              }}
            >
              <Typography size={3} whiteSpace="pre" lineHeight={2}>
                {`Hello! My name's Joel,\na software engineer\nbased in Philippines.`}
              </Typography>
              <Typography
                component="h1"
                size={20}
                weight={900}
                whiteSpace="pre"
              >
                {`I help people build\nbeautiful apps with\nbeautiful code.`}
              </Typography>
              <div
                style={{
                  display: "flex",
                  gap: "8px",
                }}
              >
                <Button
                  filled
                  iconTrailing="waving_hand"
                  size="large"
                  href="#contact"
                >
                  Say hello!
                </Button>
                <Button iconTrailing="arrow_forward" size="large">
                  See receipts
                </Button>
              </div>
              <div>{""}</div>
            </div>
          </div>
        </section>
        <section
          className={styles.section}
          style={{
            backgroundColor: "#fafafa",
            borderBottom: "solid 1px #efebe9",
          }}
        >
          <div>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                placeContent: "center",
              }}
            >
              <Typography size={3} whiteSpace="pre" lineHeight={2}>
                {`Words are boring,\nand they can lie.\nReal work can't.`}
              </Typography>
              <Typography
                component="h2"
                size={19}
                weight={900}
                whiteSpace="pre"
              >
                {`Here are my\nreceipts\nprojects.`}
              </Typography>
            </div>
            <div>{""}</div>
          </div>
        </section>
        <section
          className={styles.section}
          style={{
            backgroundColor: "#fafafa",
          }}
        >
          <div>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                placeContent: "center",
              }}
            >
              <Typography
                component="h2"
                size={19}
                weight={900}
                whiteSpace="pre"
                gutter={0.5}
              >
                {`What is beautiful?`}
              </Typography>
              <Typography size={3} whiteSpace="pre" lineHeight={2}>
                {`Beauty is in...`}
              </Typography>
            </div>
            <div>{""}</div>
          </div>
        </section>
        <section
          id="contact"
          className={styles.section}
          style={{
            backgroundColor: "#e8eaf6",
          }}
        >
          <div
            style={{
              display: "grid",
              gap: "32px",
              placeContent: "center",
            }}
          >
            <div
              style={{
                display: "flex",
                flexDirection: "column",
              }}
            >
              <Typography
                component="h2"
                size={19}
                weight={900}
                whiteSpace="pre"
                gutter={0.5}
              >
                {`Ready to build\nbeautiful?`}
              </Typography>
              <Typography size={3} whiteSpace="pre" lineHeight={2}>
                {`Say hello and let's get started.`}
              </Typography>
            </div>
            <div>
              <ContactForm />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
